/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtFlow: typeof import('./components/ArtFlow.vue')['default']
    ArtSynapse: typeof import('./components/ArtSynapse.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}
